spring:
  datasource:
#    url: jdbc:mysql://121.40.140.72:3306/fangwei?useUnicode=true&characterEncoding=utf8
#    username: fangwei
#    password: PfHibTfSGK2zaaBA
    url: jdbc:mysql://121.40.140.72:3306/wordtionary?useUnicode=true&characterEncoding=utf8
    username: wordtionary
    password: SBR2TmBNKwJnrYSP
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/hxfu/mapper/xml/*.xml
server:
  port: 2346
